# Generated by Django 6.0.2 on 2026-05-11 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0014_membershippayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='response_model',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
