# Generated by Django 6.0.2 on 2026-05-18 12:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0016_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='names',
            name='role',
            field=models.CharField(choices=[('trainer', 'Trainer'), ('trainee', 'Trainee')], default='trainee', max_length=10),
        ),
        migrations.AlterField(
            model_name='names',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='news.category'),
        ),
        migrations.AlterField(
            model_name='names',
            name='trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trainees', to=settings.AUTH_USER_MODEL),
        ),
    ]
