# Generated by Django 6.0.2 on 2026-05-18 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0017_names_role_alter_names_category_alter_names_trainer'),
    ]

    operations = [
        migrations.AddField(
            model_name='names',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='names',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
