# Generated by Django 6.0.2 on 2026-05-23 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0019_names_gender_userprofile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='names',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10, null=True),
        ),
    ]
