# Generated by Django 6.0.2 on 2026-06-04 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0021_userprofile_medical_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('session_date', models.DateTimeField()),
                ('max_trainees', models.PositiveIntegerField(default=10)),
                ('registered_trainees', models.ManyToManyField(blank=True, related_name='joined_sessions', to='news.names')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_sessions', to='news.names')),
            ],
        ),
    ]
