# Generated by Django 6.0.2 on 2026-06-04 20:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0022_trainingsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingsession',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='max_trainees',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='registered_trainees',
            field=models.ManyToManyField(blank=True, related_name='registered_sessions', to='news.names'),
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_sessions', to='news.names'),
        ),
    ]
