# Generated by Django 6.0.2 on 2026-06-06 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0025_names_preferred_trainer'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
