# Generated by Django 6.0.2 on 2026-06-15 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0026_userprofile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingsession',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AlterField(
            model_name='names',
            name='detail',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.CreateModel(
            name='TrainingSpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_spaces', to='news.category')),
            ],
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='space',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='news.trainingspace'),
        ),
    ]
