# Generated by Django 6.0.2 on 2026-06-15 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0027_trainingsession_duration_minutes_alter_names_detail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, help_text='Description shown on category catalog pages', null=True),
        ),
    ]
