# Generated by Django 6.0.2 on 2026-06-15 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0029_attendancelog_memberid'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='ai_answered',
            field=models.BooleanField(default=False),
        ),
    ]
