# Generated by Django 5.2.8 on 2026-06-20 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0031_alter_attendancelog_id_alter_bodymetric_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainerRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trainee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings_given', to='news.names')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings_received', to='news.names')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('trainee', 'trainer')},
            },
        ),
    ]
