# Generated by Django 5.2.8 on 2026-06-20 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0032_trainerrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingspace',
            name='is_under_maintenance',
            field=models.BooleanField(default=False, help_text='When checked, this space will be unavailable for session creation'),
        ),
    ]
