# Generated by Django 5.2.8 on 2026-06-20 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0033_trainingspace_is_under_maintenance'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainerChangeRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(help_text='Mandatory reason for requesting a trainer change')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('current_trainer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_requests_received', to='news.names')),
                ('trainee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_requests', to='news.names')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
