# Generated by Django 6.0.2 on 2026-07-05 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0037_alter_attendancelog_id_alter_bodymetric_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainerpayment',
            name='payment_day',
            field=models.IntegerField(default=1, help_text='Constant day of month for payment (1-28)'),
        ),
    ]
