# Generated by Django 6.0.2 on 2026-07-05 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0038_trainerpayment_payment_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='GymConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_day', models.IntegerField(default=1, help_text='Global constant pay day for all employees (1-28)')),
            ],
            options={
                'verbose_name': 'Gym Configuration',
                'verbose_name_plural': 'Gym Configuration',
            },
        ),
        migrations.RemoveField(
            model_name='trainerpayment',
            name='payment_day',
        ),
    ]
