# Generated by Django 6.0.2 on 2026-07-05 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0039_gymconfig_remove_trainerpayment_payment_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainerschedule',
            name='shift',
            field=models.CharField(choices=[('morning', 'Morning'), ('day', 'Day'), ('evening', 'Evening')], default='morning', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='trainerschedule',
            unique_together={('trainer', 'day_of_week', 'shift')},
        ),
        migrations.RemoveField(
            model_name='trainerschedule',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='trainerschedule',
            name='start_time',
        ),
    ]
