# Generated by Django 6.0.2 on 2026-07-05 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0040_alter_trainerschedule_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainerschedule',
            name='shift',
            field=models.CharField(choices=[('0600-0900', '06:00–09:00'), ('0900-1200', '09:00–12:00'), ('1200-1500', '12:00–15:00'), ('1500-1800', '15:00–18:00'), ('1800-2100', '18:00–21:00'), ('2100-2300', '21:00–23:00')], default='0600-0900', max_length=10),
        ),
    ]
