# Generated by Django 6.0.2 on 2026-07-05 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0041_alter_trainerschedule_shift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainerschedule',
            name='shift',
            field=models.CharField(choices=[('day', 'Day'), ('evening', 'Evening')], default='day', max_length=10),
        ),
    ]
