# Generated by Django 5.2.8 on 2026-07-08 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0043_trainerschedule_comment_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SplitProgression',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_day_index', models.IntegerField(default=0, help_text='Current day index in the split cycle')),
                ('total_workouts_completed', models.IntegerField(default=0, help_text='Total number of workouts completed')),
                ('last_workout_date', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trainee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='split_progression', to='news.names')),
            ],
        ),
    ]
