# Generated by Django 5.2.8 on 2026-07-08 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0044_splitprogression'),
    ]

    operations = [
        migrations.AddField(
            model_name='splitprogression',
            name='planned_days_per_week',
            field=models.IntegerField(default=3, help_text='Number of days planned to train per week'),
        ),
    ]
