# Generated by Django 5.2.8 on 2026-07-17 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0045_splitprogression_planned_days_per_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershippayment',
            name='chapa_tx_ref',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='membershippayment',
            name='subscription_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='membershippayment',
            name='subscription_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='membershippayment',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('TRANSFER', 'Bank Transfer'), ('CHAPA', 'Chapa'), ('OTHER', 'Other')], max_length=50),
        ),
    ]
