# Generated by Django 5.2.8 on 2026-07-21 22:50

from django.db import migrations


def fix_ai_chat_read_status(apps, schema_editor):
    response_model = apps.get_model('news', 'response_model')
    questions = apps.get_model('news', 'questions')
    
    ai_questions = questions.objects.filter(ai_answered=True)
    response_model.objects.filter(quest__in=ai_questions, is_read=False).update(is_read=True)


def reverse_fix(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0046_membershippayment_chapa_tx_ref_and_more'),
    ]

    operations = [
        migrations.RunPython(fix_ai_chat_read_status, reverse_fix),
    ]
