# Generated by Django 5.2.8 on 2026-07-27 09:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0047_fix_ai_chat_read_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='feed_posts/')),
                ('quote', models.TextField(blank=True, help_text='A motivational quote or message')),
                ('hashtags', models.CharField(blank=True, help_text='Space or comma separated hashtags e.g. #fitness #gym', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_posts', to=settings.AUTH_USER_MODEL)),
                ('hyped_by', models.ManyToManyField(blank=True, related_name='hyped_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
