
from django.contrib import admin
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views
from news.views import landing,admin_dash,admin_trainer_dashboard,gym_config_view,employee_payments_list,employee_payment_edit,employee_payment_delete,home,members,Category_view,detail,about,contact,register,edit,delete_member,comm_edit,comm_delete,category_list,delete_cat,cat_edit,ques_list,ques_edit,signup,loginUser,logoutUser,user_list,manage_members,manage_staff,delete_user,delete_legacy_member,edit_legacy_member,ques_delete,response,response_list,response_edit,response_delete,record_payment,trainer_and_categories_list,trainer_category_selector,trainer_and_categories_api,trainer_tracker,assign_trainer,trainee_settings,trainee_update_account,trainee_medical_info,create_session,register_session,trainee_session_list,trainer_session_registrations,session_hub,user_profile,telegram_broadcast,trainee_bmi,trainer_bmi_tracker,trainer_settings,trainer_update_account,training_space_list,training_space_edit,training_space_delete,training_space_toggle_maintenance,api_available_spaces,category_catalog,my_id_card,regenerate_qr,regenerate_all_qr_codes,generate_all_missing_ids,id_card_pdf,admin_scan_qr,admin_scan_checkin,admin_scan_checkout,record_attendance,scan_entry,check_in_entry,check_out_entry,attendance_log_view,attendance_dashboard,chat_page,chat_api,registrar_dashboard,registrar_register,registrar_scan_qr,registrar_scan_checkout,registrar_attendance_log,registrar_currently_in,trainer_currently_in,create_desk,rate_trainer,trainer_ratings_dashboard,trainer_my_feedback,request_trainer_change,training_plan_view,trainer_schedules_list,trainer_schedule_edit,trainer_schedule_delete,trainer_my_schedule,trainer_workout_tracking,reset_trainee_split,debug_email,membership_payment_page,chapa_checkout,payment_receipt
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/qr-scanner/', admin_scan_qr, name='admin_scan_qr_url'),
    path('admin/qr-checkin/', admin_scan_checkin, name='admin_scan_checkin_url'),
    path('admin/qr-checkout/', admin_scan_checkout, name='admin_scan_checkout_url'),
    path('admin/attendance-dashboard/', attendance_dashboard, name='attendance_dashboard_url'),
    path('admin/generate-all-ids/', generate_all_missing_ids, name='generate_all_ids_url'),
    path('admin/regenerate-all-qr-codes/', regenerate_all_qr_codes, name='regenerate_all_qr_codes_url'),
    path('admin/gym-config/', gym_config_view, name='gym_config_url'),
    path('admin/trainer-dashboard/', admin_trainer_dashboard, name='admin_trainer_dashboard_url'),
    path('admin/trainer-schedules/', trainer_schedules_list, name='trainer_schedules_url'),
    path('admin/trainer-schedule/edit/<int:schedule_id>/', trainer_schedule_edit, name='trainer_schedule_edit_url'),
    path('admin/trainer-schedule/delete/<int:schedule_id>/', trainer_schedule_delete, name='trainer_schedule_delete_url'),
    path('admin/employee-payments/', employee_payments_list, name='employee_payments_url'),
    path('admin/employee-payment/edit/<int:payment_id>/', employee_payment_edit, name='employee_payment_edit_url'),
    path('admin/employee-payment/delete/<int:payment_id>/', employee_payment_delete, name='employee_payment_delete_url'),
    path('admin/', admin.site.urls),
    path('admin-portal/',admin_dash,name='admin_url'),
    path('home/',home,name='home_url'),
    path('about/',about,name='about_url'),
    path('contact/',contact,name='contact_url'),
    path('register/',register,name='register_url'),
    path('members/',members,name='members_url'),
    path('category/<str:category_name>/', category_catalog, name='category_catalog_url'),
    path('category_view/<str:category_name>',Category_view,name='Category_view_url'),
    path('detail/<str:name>',detail,name='detail_url'),
    path('category_list/',category_list,name='cat_list_url'),
    path('edit/<str:name>/',edit,name='edit_url'),
    path('delete/<str:name>/', delete_member, name='delete_m_url'),
    path('comment_edit/<int:comment_id>/', comm_edit, name='comm_edit_url'),
    path('delete_comment/<int:comment_id>/',comm_delete, name='comm_delete_url'),
    path('delete_cat/<int:cat_id>/',delete_cat,name='delete_cat_url'),
    path('category/edit/<int:cat_id>/', cat_edit, name='cat_edit_url'),
    path('questions-log/',ques_list , name='ques_list_url'),
    path('edit-question/<int:q_id>/', ques_edit, name='ques_edit_url'),
    path('ques_delete/<int:q_id>/',ques_delete,name='ques_delete_url'),
    path('response/<int:q_id>/',response,name='response_url'),
    path('response_list/',response_list,name='response_list_url'),
    path('response_edit/<int:r_id>/',response_edit,name='response_edit_url'),
    path('response_delete/<int:r_id>/',response_delete, name='response_delete_url'),
    path('signup/', signup, name='signup_url'),
    path('', landing, name='landing_url'),
    path('login/', loginUser, name='login_url'),
    path('logout/', logoutUser, name='logout_url'),
    path('password-change/', auth_views.PasswordChangeView.as_view(template_name='password_change.html', success_url=reverse_lazy('password_change_done_url')), name='password_change_url'),
    path('password-change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='password_change_done.html'), name='password_change_done_url'),
    path('manage-users/', user_list, name='user_management_url'),
    path('manage-members/', manage_members, name='manage_members_url'),
    path('manage-staff/', manage_staff, name='manage_staff_url'),
    path('delete-user/<int:user_id>/', delete_user, name='delete_user_url'),
    path('delete-legacy/<int:member_id>/', delete_legacy_member, name='delete_legacy_member_url'),
    path('edit-legacy/<int:member_id>/', edit_legacy_member, name='edit_legacy_member_url'),
    path('record-payment/', record_payment, name='record_payment_url'),
    path('trainers-and-types/', trainer_and_categories_list, name='trainer_categories_url'),
    path('trainer-selector/', trainer_category_selector, name='trainer_selector_url'),
    path('api/trainers-categories/', trainer_and_categories_api, name='trainer_categories_api_url'),
    path('tracker/', trainer_tracker, name='trainer_tracker_url'),
    path('assign-trainer/', assign_trainer, name='assign_trainer_url'),
    path('settings/', trainee_settings, name='trainee_settings_url'),
    path('settings/account/', trainee_update_account, name='trainee_account_url'),
    path('settings/medical/', trainee_medical_info, name='trainee_medical_url'),
    path('trainer-settings/', trainer_settings, name='trainer_settings_url'),
    path('trainer-settings/account/', trainer_update_account, name='trainer_account_url'),
    path('session/create/', create_session, name='create_session_url'),
    path('session/hub/', session_hub, name='session_hub_url'),
    path('session/register/<int:session_id>/', register_session, name='register_session_url'),
    path('trainer-sessions/', trainee_session_list, name='trainee_sessions_url'),
    path('trainer-session-registrations/', trainer_session_registrations, name='trainer_session_registrations_url'),
    path('bmi/', trainee_bmi, name='trainee_bmi_url'),
    path('trainer-bmi/', trainer_bmi_tracker, name='trainer_bmi_tracker_url'),
    path('profile/<int:user_id>/', user_profile, name='user_profile_url'),
    path('trainer/currently-in/', trainer_currently_in, name='trainer_currently_in_url'),
    path('telegram-broadcast/', telegram_broadcast, name='telegram_broadcast_url'),
    path('training-spaces/', training_space_list, name='training_space_list_url'),
    path('training-space/edit/<int:space_id>/', training_space_edit, name='training_space_edit_url'),
    path('training-space/toggle-maintenance/<int:space_id>/', training_space_toggle_maintenance, name='training_space_toggle_maintenance_url'),
    path('training-space/delete/<int:space_id>/', training_space_delete, name='training_space_delete_url'),
    path('api/available-spaces/', api_available_spaces, name='api_available_spaces_url'),
    path('my-id-card/', my_id_card, name='my_id_card_url'),
    path('my-id-card/regenerate-qr/', regenerate_qr, name='regenerate_qr_url'),
    path('id-card-pdf/', id_card_pdf, name='id_card_pdf_url'),
    path('api/record-attendance/', record_attendance, name='record_attendance_url'),
    path('api/scan-entry/', scan_entry, name='scan_entry_url'),
    path('api/check-in/', check_in_entry, name='check_in_entry_url'),
    path('api/check-out/', check_out_entry, name='check_out_entry_url'),
    path('attendance-log/', attendance_log_view, name='attendance_log_url'),
    path('chat/', chat_page, name='chat_url'),
    path('api/chat/', chat_api, name='chat_api_url'),

    # Registrar URLs
    path('registrar/dashboard/', registrar_dashboard, name='registrar_dashboard_url'),
    path('registrar/register/', registrar_register, name='registrar_register_url'),
    path('registrar/scan-qr/', registrar_scan_qr, name='registrar_scan_qr_url'),
    path('registrar/scan-checkout/', registrar_scan_checkout, name='registrar_scan_checkout_url'),
    path('registrar/attendance-log/', registrar_attendance_log, name='registrar_attendance_log_url'),
    path('registrar/currently-in/', registrar_currently_in, name='registrar_currently_in_url'),
    path('create-desk/', create_desk, name='create_desk_url'),
    path('rate-trainer/<str:trainer_name>/', rate_trainer, name='rate_trainer_url'),
    path('trainer-ratings/', trainer_ratings_dashboard, name='trainer_ratings_url'),
    path('trainer-my-feedback/', trainer_my_feedback, name='trainer_my_feedback_url'),
    path('request-trainer-change/<str:trainer_name>/', request_trainer_change, name='request_trainer_change_url'),
    path('training-plan/<int:trainee_id>/', training_plan_view, name='training_plan_url'),
    path('trainer/my-schedule/', trainer_my_schedule, name='trainer_my_schedule_url'),
    path('trainer/workout-tracking/', trainer_workout_tracking, name='trainer_workout_tracking_url'),
    path('trainer/reset-split/<int:trainee_id>/', reset_trainee_split, name='reset_trainee_split_url'),
    path('debug-email/', debug_email, name='debug_email_url'),
    path('membership/pay/', membership_payment_page, name='membership_payment_url'),
    path('membership/checkout/', chapa_checkout, name='chapa_checkout_url'),
    path('membership/receipt/<int:payment_id>/', payment_receipt, name='payment_receipt_url'),
    ]
from django.conf import settings
from django.conf.urls.static import static

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
